name: Build and deploy Python app to Azure Web App - skraafoto-plandata

on:
  push:
    branches:
      - Azure-SQLite-GeoPackage
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # ✅ Checkout source code and include LFS files
      - uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      # ✅ Ensure Git LFS files (like .gpkg) are downloaded
      - name: Pull LFS files
        run: |
          git lfs install
          git lfs pull
          ls -lh plandata.gpkg || echo "GeoPackage not found!"

      # ✅ Setup Python
      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # ✅ Install dependencies (build check)
      - name: Install dependencies
        run: |
          python -m venv antenv
          source antenv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      # ✅ Upload artifacts (skips virtualenv)
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !antenv/
            !.git/
            !.github/
            !__pycache__/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_AC7A19752006419F83D9A5308DBBBCB8 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_25BA7C8F94024606B904893E1FB72324 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DD74700945D346EBB597564674EA99FB }}

      # ✅ Deploy to your Azure Web App
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'skraafoto-plandata'
          slot-name: 'Production'
          package: .
          clean: true
          type: zip


